name: Check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31.5.2
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run flake check
        run: nix flake check
